---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cpmeyhn5897/public_html/
    - /bin/rsync -av --delete --exclude='.git' --exclude='.env' --exclude='storage' --exclude='*.zip' ./ $DEPLOYPATH
    - /bin/chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache
